export default [
  {
    id: '1_product',
    name: 'lorem ipsum',
    description: 'lorem ipsum',
    address: 'lorem ipsum dolor',
    fullAddress: 'lorem ipsum dolor',
    avatar: '',
    longitute: '',
    latitude: '',
    userId: '1_user',
  },
  {
    id: '2_product',
    name: 'lorem ipsum',
    description: 'lorem ipsum',
    address: 'lorem ipsum dolor',
    fullAddress: 'lorem ipsum dolor',
    avatar: '',
    longitute: '',
    latitude: '',
    userId: '1_user',
  },
  {
    id: '3_product',
    name: 'lorem ipsum',
    description: 'lorem ipsum',
    address: 'lorem ipsum dolor',
    fullAddress: 'lorem ipsum dolor',
    avatar: '',
    longitute: '',
    latitude: '',
    userId: '1_user',
  },
]
