export default [
  {
    id: '1_product',
    year: '2000',
    price: '10000',
    currency: 'uero',
    description: 'lorem ipsum dolor',
    topImage: '',
    crownSideImage: '',
    crownBackImage: '',
    showOffImage: '',
    referenceId: '1_reference',
    conditionId: '1_condition',
    accompanyId: '1_accompany',
    boutiqueId: '1_boutique',
    productStatusId: '1_productStatus',
    matchProductId: '1_matchProduct',
  },
  {
    id: '2_product',
    year: '2000',
    price: '20000',
    currency: 'usd',
    description: 'lorem ipsum dolor',
    topImage: '',
    crownSideImage: '',
    crownBackImage: '',
    showOffImage: '',
    referenceId: '2_reference',
    conditionId: '2_condition',
    accompanyId: '2_accompany',
    boutiqueId: '2_boutique',
    productStatusId: '2_productStatus',
    matchProductId: '2_matchProduct',
  },
  {
    id: '3_product',
    year: '2000',
    price: '30000',
    currency: 'uero',
    description: 'lorem ipsum dolor',
    topImage: '',
    crownSideImage: '',
    crownBackImage: '',
    showOffImage: '',
    referenceId: '3_reference',
    conditionId: '3_condition',
    accompanyId: '3_accompany',
    boutiqueId: '3_boutique',
    productStatusId: '3_productStatus',
    matchProductId: '3_matchProduct',
  },
]
