export default [
  {
    id: '1_user',
    firstName: 'lala',
    middleName: 'x',
    lastName: 'lili',
    email: 'lala@mail.com',
    username: 'lala',
    password: 'lalapass',
    googleConnect: '',
    appleConnect: '',
    facebookConnect: '',
    mobile: '',
    picture: '',
    config: '',
    roleId: '',
    subcriptionId: '',
    statusId: '',
  },
  {
    id: '2_user',
    firstName: 'jhon',
    middleName: 'x',
    lastName: 'doe',
    email: 'jhon@mail.com',
    username: 'jhon',
    password: 'jhonpass',
    googleConnect: '',
    appleConnect: '',
    facebookConnect: '',
    mobile: '',
    picture: '',
    config: '',
    roleId: '',
    subcriptionId: '',
    statusId: '',
  },
]
