export default [
  {
    id: "1_model",
    referenceNumber: "1_lorem ipsum",
    caseMaterial: "1_lorem ipsum dolor",
    caseDiameter: "1_lorem ipsum dolor",
    caseThickness: "1_lorem ipsum dolor",
    waterResistance: "1_lorem ipsum dolor",
    glass: "1_lorem ipsum",
    streetName: "1_lorem ipsum ",
    lugWidth: "1_lorem ipsum",
    introduceAt: "1_lorem ipsum",
    discontinueAt: "1_lorem ipsum",
    powerReserved: "1_lorem ipsum",
    numberOfJewel: "1_lorem ipsum",
    dialNumeral: "1_lorem ipsum",
    otherInfo: "1_lorem ipsum",
    collectionId: '1_collection',
    caliberId: "1_caliber",
    movementId: "1_movement",
    bezelMaterialId: "1_material",
    dialMaterialId: "1_material",
    braceletMaterialId: "1_material",
    braceletColorId: "1_color",
    claspId: "1_clasp",
    claspMaterialId: "1_material",
    functionId: "1_function",
  },
  {
    id: "2_model",
    referenceNumber: "2_lorem ipsum",
    caseMaterial: "2_lorem ipsum dolor",
    caseDiameter: "2_lorem ipsum dolor",
    caseThickness: "2_lorem ipsum dolor",
    waterResistance: "2_lorem ipsum dolor",
    glass: "2_lorem ipsum",
    streetName: "2_lorem ipsum ",
    lugWidth: "2_lorem ipsum",
    introduceAt: "2_lorem ipsum",
    discontinueAt: "2_lorem ipsum",
    powerReserved: "2_lorem ipsum",
    numberOfJewel: "2_lorem ipsum",
    dialNumeral: "2_lorem ipsum",
    otherInfo: "2_lorem ipsum",
    collectionId: '2_collection',
    caliberId: "2_caliber",
    movementId: "2_movement",
    bezelMaterialId: "2_material",
    dialMaterialId: "2_material",
    braceletMaterialId: "2_material",
    braceletColorId: "2_color",
    claspId: "2_clasp",
    claspMaterialId: "2_material",
    functionId: "2_function",
  },
  {
    id: "3_model",
    referenceNumber: "3_lorem ipsum",
    caseMaterial: "3_lorem ipsum dolor",
    caseDiameter: "3_lorem ipsum dolor",
    caseThickness: "3_lorem ipsum dolor",
    waterResistance: "3_lorem ipsum dolor",
    glass: "3_lorem ipsum",
    streetName: "3_lorem ipsum ",
    lugWidth: "3_lorem ipsum",
    introduceAt: "3_lorem ipsum",
    discontinueAt: "3_lorem ipsum",
    powerReserved: "3_lorem ipsum",
    numberOfJewel: "3_lorem ipsum",
    dialNumeral: "3_lorem ipsum",
    otherInfo: "3_lorem ipsum",
    collectionId: '3_collection',
    caliberId: "3_caliber",
    movementId: "3_movement",
    bezelMaterialId: "3_material",
    dialMaterialId: "3_material",
    braceletMaterialId: "3_material",
    braceletColorId: "3_color",
    claspId: "3_clasp",
    claspMaterialId: "3_material",
    functionId: "3_function",
  },
]
